services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Host:Container
    volumes:
      - ./backend:/app
    command: make run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Host:Container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run serve
